artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1c6ByHwx7b1cf47C8lAMcpBtnY3ke5-Lk/view?usp=sharing
  local_data_file: artifacts/data_ingestion/Dataset.csv
  unzip_dir: artifacts/data_ingestion